language: cpp

sudo: false

compiler:
  - gcc

env:
  matrix:
    - COMPILER=g++-5 CCOMPILER=gcc-5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - g++-5
      - libssh2-1-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - libmysqlcppconn-dev
      - cmake
      - cmake-data

before_script:
  - export CXX=$COMPILER CC=$CCOMPILER
  - cmake --version
  - mkdir build
  - cd build
  - cmake -LAH ..

script:
  - make VERBOSE=1

notifications:
  slack: ra-leadership:chIuc5mdb4fPiAx9t4TPj0Rr
