language: cpp

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      env:
        - COMPILER=clang++-3.7
        - LLVM_VERSION=3.7.0
        - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz

before_script:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update -q
  - sudo apt-get install libssh2-1-dev libssl-dev libcurl4-openssl-dev libmysqlcppconn-dev cmake cmake-data -y
  - 
    if [ -z "$LLVM_ARCHIVE_PATH" ]; then
      wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH;
      mkdir $HOME/clang+llvm;
      tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang+llvm --strip-components 1;
      export PATH=$HOME/clang+llvm/bin:$PATH;
    fi
  - export CXX=$COMPILER CC=$CCOMPILER
  - cmake --version
  - mkdir build
  - cd build
  - cmake -LAH ..

script:
  - make VERBOSE=1

notifications:
  slack: ra-leadership:chIuc5mdb4fPiAx9t4TPj0Rr