language: cpp

sudo: false

compiler:
  - gcc
  - clang

env:
  matrix:
    - COMPILER=g++-4.9 CCOMPILER=gcc-4.9
matrix:
  include:
    # gcc 
    - env: COMPILER=g++-5 CCOMPILER=gcc-5
      addons:
        apt:
          packages: g++-5
          sources: *sources

    # Clang 3.7
    - env: 
      - COMPILER=clang++-3.7 CCOMPILER=clang-3.7
      - global:
        - LLVM_VERSION=3.7.0
        - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz

    # Xcode 6.4
    - os: osx
      env: COMPILER=clang++ CCOMPILER=clang
      osx_image: xcode6.4

    # Xcode 7
    - os: osx
      env: COMPILER=clang++ CCOMPILER=clang BREW_CMAKE=ON
      osx_image: xcode7
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3  
    sources: &sources
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libssh2-1-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - libmysqlcppconn-dev
      - cmake
      - cmake-data

before_script:
  - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
  - mkdir $HOME/clang+llvm
  - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang+llvm --strip-components 1
  - export PATH=$HOME/clang+llvm/bin:$PATH
  - export CXX=$COMPILER CC=$CCOMPILER
  - cmake --version
  - mkdir build
  - cd build
  - cmake -LAH ..

script:
  - make VERBOSE=1

notifications:
  slack: ra-leadership:chIuc5mdb4fPiAx9t4TPj0Rr
