language: cpp

sudo: false

compiler:
  - gcc
  - clang

env:
  matrix:
    - COMPILER=g++-4.9 CCOMPILER=gcc-4.9
matrix:
  include:
    # gcc 5
    - env: COMPILER=g++-5 CCOMPILER=gcc-5
      addons:
        apt:
          packages: g++-5
          sources: *sources

    # Clang 3.4
    - env: COMPILER=clang++ CCOMPILER=clang LINUX_CLANG=1
      addons:
        apt:
          packages: clang-3.4
          sources: *sources

    # Clang 3.5
    - env: COMPILER=clang++-3.5 CCOMPILER=clang-3.5
      addons:
        apt:
          packages: clang-3.5
          sources: *sources

    # Clang 3.6
    - env: COMPILER=clang++-3.6 CCOMPILER=clang-3.6
      addons:
        apt:
          packages: clang-3.6
          sources: *sources

    # Clang 3.7
    - env: COMPILER=clang++-3.7 CCOMPILER=clang-3.7
      addons:
        apt:
          packages: clang-3.7
          sources: *sources

    # Clang 3.8
    - env: COMPILER=clang++-3.8 CCOMPILER=clang-3.8
      addons:
        apt:
          packages: clang-3.8
          sources: *sources

    # Xcode 6.4
    - os: osx
      env: COMPILER=clang++ CCOMPILER=clang
      osx_image: xcode6.4

    # Xcode 7
    - os: osx
      env: COMPILER=clang++ CCOMPILER=clang BREW_CMAKE=ON
      osx_image: xcode7
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3  
    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise-3.8
    packages:
      - g++-5
      - libssh2-1-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - libmysqlcppconn-dev
      - cmake
      - cmake-data

before_script:
  - export CXX=$COMPILER CC=$CCOMPILER
  - cmake --version
  - mkdir build
  - cd build
  - cmake -LAH ..

script:
  - make VERBOSE=1

notifications:
  slack: ra-leadership:chIuc5mdb4fPiAx9t4TPj0Rr
